### ISSUE TITLE
error when pasting unicode

### ISSUE THREAD

**Issue by breja** [veonim/veonim#110]

**Comment by deomitrus** [comment]
i was having issues copying unicode from teh webz. verify

**Comment by deomitrus** [comment]
×

**Comment by goavn** [comment]
works fine on linux (gallium)

**Comment by goavn** [comment]
on remote macos test case turns to ?

**Comment by deomitrus** [comment]
does it have anything to do with the clipboard provider on the operating system? i wonder if using the electron clipboard facilities in any way would help with this. it might be worth testing it out and seeing what happens

**Comment by breja** [comment]
tested and works on macos

not an issue with our code anyways since clipboard does not go thru our input code
