### ISSUE TITLE
npm 5.4.0 breaks everything - spawn eacces

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#111]
7zip module in build process and running veonim spawn eacces in bin launcher. 

# dammit npm WTF

**Comment by deomitrus** [comment]
![](https://media.giphy.com/media/QA88yMhazfDI4/giphy.gif)

**Comment by goavn** [comment]
not seeing this on linux + npm 5.5.1 + pack-linux

**Comment by deomitrus** [comment]
not seeing this on mac + npm 5.5.1 + release
