### ISSUE TITLE
markdown + html + vim syntax colors hovers/hints

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#121]

**Comment by deomitrus** [comment]
what about rendering to syntax html like github markdown. then get group colors from vim. then match syntax groups

md syntax class name: variable?
vim hl grp: jsVar

??? maybe???

**Comment by deomitrus** [comment]
```vimscript
"bd!
fun! Colors()
  let colors = []
  let chars = split(getline(1), '\zs')
  let strLen = len(chars)
  let col = 1
  let lastColor = ''
  let fg = synIDattr(hlID("Normal"), "fg#")

  while col <= strLen
    let clr = synIDattr(synIDtrans(synID(1, col, 1)), "fg#")
    if clr != lastColor
      if clr == ''
        let clr = fg
      endif
      call add(colors, [col - 1, clr])
    endif
    let lastColor = clr
    let col += 1
  endwhile

  return colors
endfun
```

**Comment by deomitrus** [comment]
spawn vim instance. set attributes. paste text, get colors, return, do cleanup.

set attributes on every single call? globally before? how know when colorscheme changes?

**Comment by goavn** [comment]
remove markdown then syntax highlight https://www.npmjs.com/package/remove-markdown
