### ISSUE TITLE
redux devtools?

### ISSUE THREAD

**Issue by breja** [veonim/veonim#135]

**Comment by deomitrus** [comment]
hmr?

**Comment by deomitrus** [comment]
how does it work with a whole bunch of separate states?

**Comment by goavn** [comment]
redux devtools supports multiple instances

snippet:
To identify stores you can pass the instanceId parameter to the enhancer: `window.devToolsExtension({ name: 'Widget', instanceId: 'widgetId' })`
It's not required. If this parameter is not specified, there will be generated a random id.

from here:
https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.0

**Comment by deomitrus** [comment]
look at lukejacksonn/hyperapp-electron

**Comment by deomitrus** [comment]
not now. redux devtools requires wrapping each app in a higher order app. that sounds like too much work and i'm lazy.

**Comment by breja** [comment]
will do it
