### ISSUE TITLE
grep files timeout expire bug?

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#139]
like in fs-fuzzy?

**Comment by goavn** [comment]
should not be an issue...

files would do ONE query for files in proj dir, then on query changes would simply filter the one and only response.

grep fires a new query for each query change.

still, it would be good to clean it up
- on timeout, don't clear out query and results
- invert `!noFilter` boolean logic

**Comment by deomitrus** [comment]
GOOD
