### ISSUE TITLE
task runner

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#141]
some lang server vsc extensions will populate some lang-specific tasks.

reuse tasks.json from vscode?

where will results be displayed? :term? reuse existing terms?

hook into shortcuts (vimrc)

**Comment by goavn** [comment]
for command output we can probably have a few options

- silent - no output or redirect (like maybe if the output will be quickfix list... although at that point should just use makeprg)
- default - bottom split like in vscode. creates a new :term and new bottom split that spans across all splits
- advanced - creates a new :term called `veonim-output` or w.e. for output. does not create split for it. user will open it up in a tab/split/or do whatevs. will re-use output :term on subsequent runs

these settings can be customized in vimrc

**Comment by goavn** [comment]
see: https://code.visualstudio.com/docs/editor/tasks

**Comment by goavn** [comment]
what i really want to do. should be able to do native in vim minus the shift+ctrl keybind
```vim
au! # BufEnter *.js call VeonimKeyBind('shift+ctrl+r', {-> VeonimRun('npm run build', 'advanced')})
```

**Comment by goavn** [comment]
yeah i think implementing the tasks api is too much right now. the problem matchers look promising if there is a decision to incorporate a custom problems/quickfix window in html.

for my use cases, neomake (fancy :make/makeprg) should do most

the other interesting scenario is picking up jump locations based on columns + rows from more detaiedl command outputs. for example, mocha/jest/test runners/etc which show additional info (assertion diffs, etc.) besides errors + line numbers.

this would be a case where parsing the jump locations into the quickfix list AND allowing output in a **customizable** terminal window (i.e. not stuck and limited like in vscode) would be beneficial

**Comment by deomitrus** [comment]
i got this working in vimscript

```vim
call VK('s-c-r', {->jobstart('npm start')})
call VK('s-c-t', {->execute('badd term://npm run test-watch')})
call VK('s-c-o', {->termopen('npm test')})
call VK('s-c-|', {->execute('Veonim devtools')})
```

i think the other missing pieces is to 
- define a FUZZY FIND MENU dictionary of task name -> task run options (background, bg term, term) + task cmd
- define different tasks per filetype (can use ft autocmds for this)

**Comment by deomitrus** [comment]
good and done thanks
