### ISSUE TITLE
upgrade vim 0.2.2

### ISSUE THREAD

**Issue by ghost** [veonim/veonim#159]
- [x] read api docs (api stuff is in `:h ui`)
- [x] use new vim hl id/name apis to get color info
- [x] `:h api-metadata` new `ui_events` what is it and can we use it?
- [x] figure out about this `appimage` thing (tracked separately in #183)
- [x] upgrade neovim binary dep
- [x] use optionalDependency: os in neovim binary dep repo? (see `7zip-bin` and https://docs.npmjs.com/files/package.json#os)
- [x] build new neovim
- [x] test new neovim

**Comment by deomitrus** [comment]
i'm not seeing the new docs. iswearisawthemearlier in 0.2.1 release!

**Comment by deomitrus** [comment]
docs exist in binary release download...

**Comment by deomitrus** [comment]
oh when it runs in devmode it uses parent nvim docs. building dmg uses own docs
