### ISSUE TITLE
explorer - jump to specific path (like ctrl + g in finder)

### ISSUE THREAD

**Issue by breja** [veonim/veonim#169]

**Comment by deomitrus** [comment]
would be nice to have tab-completion support for this, so this makes this task a little more complex

**Comment by deomitrus** [comment]
could be similar with path autocomplete #201

**Comment by breja** [comment]
or maybe we skip the autocomplete for this right now and just IMPLEMENT IT LIVE. WE'LL DO IT LIVE

**Comment by breja** [comment]
GOTEM
