### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#2]
- use ast for additional text objects (identify object key/values, function bodies, etc.)
- observables (kefir/highland) for key-transforms?
- theme editor/color pickr
- theme/colorscheme switcher menu (show major colors palette?)
- git view: overlay on left (like vscode) - select files and open in new vim tab git diff split view via fugitive
- yankring via overlay menu selector (show different registers contents)
- save macros to diff registers/ui to select saved macros or previous macros
- splash screen
- helm (discoverability menu)
- status bar
- lulz
- blur
- generic fuzzy find list api (allow user defined list input -> result output - i.e. basically fzf with pretty gui)
- undotree
- macro library (e.g. convert object to vars <->)

cleanup
- plugin manager - (request -> r2)
- huu module self-container (+ hyperapp, etc.)

**Comment by goavn** [comment]
https://developers.google.com/web/updates/2016/06/css-containment

since each plugin component is independent?

**Comment by goavn** [comment]
snippets - this will largely depend on extended marks _coming soon_™ to neovim

**Comment by goavn** [comment]
fuzzy search by line (popup window) - highlight line when jumping to selection

**Comment by goavn** [comment]
blurred bg popups

most popups will be over canvas. thus need to extract canvas section and apply blur filter on section + position below popup + transparency on popup

**Comment by deomitrus** [comment]
functional ideas have been extracted to working issues. the rest will be populated in the wiki.
