### ISSUE TITLE
can include roboto bundled?

### ISSUE THREAD

**Issue by breja** [veonim/veonim#203]

**Comment by deomitrus** [comment]
using bundled font causes rendering glitches in calculating proper font height/widths. i wonder if it's a timing issue where the font h/w calcs are done before font is loaded. either that or the bundled font is different somehow than what exists on the system.

will need to investigate further...

```
@font-face {
  font-family: 'Roboto Mono';
  src: url('../assets/roboto-mono.ttf');
}
```

**Comment by deomitrus** [comment]
precalc font heights/widths?

**Comment by breja** [comment]
need to put together a demo of both and see what the differences are

**Comment by breja** [comment]
dirty hack meh. i think we need to render inverted cursor (and cursorline?) in canvas so the positioning of the letter is corrrrrrrrrrect
