### ISSUE TITLE
figure out strategy to allow max amount of rows inside a vim window (no empty spaces at bottom)

### ISSUE THREAD

**Issue by breja** [veonim/veonim#214]
naive approach would be to calc minimum available rows. but that doesn't solve the problem as there would be windows with empty gaps at the bottom.

i think a better approach is to go back to the scroll overflow. it kinda worked but not really

**Comment by deomitrus** [comment]
- [x] size canvas to Max(vimWindow.height OR canvas.height)
- [ ] when cursor is outta bounds, ctrl-e to shift vim window up...?

**Comment by deomitrus** [comment]
c-e/y doesn't work in stuff like terminal

**Comment by deomitrus** [comment]
i mean it does, but it doesn't

**Comment by breja** [comment]
scrolling outtabounds kthx
