### ISSUE TITLE
Question: Linux build?

### ISSUE THREAD

**Issue by edubxb** [veonim/veonim#275]
veonim looks promising, but I'm Linux user and the latest releases only have OS X builds, do you have plans to make the Linux one?

Thanks!

**Comment by deomitrus** [comment]
Yes, absolutely. I plan to have cross-platform builds (Linux, Mac OS, and Windows).

In the mean time, you may also be interested in Oni https://github.com/onivim/oni

**Comment by edubxb** [comment]
Yeah! I tried Oni and Gonvim, so it's time to try Veonim 😉 

Thanks!
