### ISSUE TITLE
find references - jump from relative location (highlight?)

### ISSUE THREAD

**Issue by breja** [veonim/veonim#302]
so i can do this. operates relative from current line

`:Veonim next-usage`
`:Veonim prev-usage`

**Comment by deomitrus** [comment]
it works because i copied the logic from diagnostics

however, just like diagnostics it needs to do a few extra things:
- loopback to beginning or end of list when restart end slingshot pingpong etc
- work across multiple files

**Comment by breja** [comment]
works nice thanks
