### ISSUE TITLE
User guide?

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#408]
Hello,

I've been watching this repo for the last couple of weeks/months and apart from the impressive progress you're making, your commit messages alone make it worth following! :)

I thought I would Veonim but couldn't go beyond opening a file files with the `e` command. 

Is there a way I can discover the available commands? I'd like to open a folder as a project and test out the different features mentioned in the readme (fuzzy finder, language servers).

Thanks,

Balint

**Comment by breja** [comment]
Hey thanks for the interest in Veonim! 😃 

Veonim is still early alpha/experimental so I can't guarantee sunshine and rainbows just yet. I did however start drafting some documentation: [docs/readme.md](../tree/master/docs/readme.md)

To answer your question specifically (as an example):

1. add javascript/typescript language server extension to `init.vim`:
```vim
if exists('veonim')
VeonimExt 'vscode:extension/sourcegraph.javascript-typescript'
endif
```

you should see some notifications that indicates extensions are installing and installation succeeded/failed 
<img width="398" alt="screen shot 2018-07-06 at 12 26 00 am" src="https://user-images.githubusercontent.com/2581815/42359922-6ce93114-80b3-11e8-90da-e5e80af59019.png">


2. open up a project folder:
```vim
:cd ~/Documents/awesome-js-project
```
or you can use the fuzzy directory menu
```vim
:Veonim change-dir ~/Documents
```

3. fuzzy find + open a `.js` file:
```
:Veonim files
```

4. if the language server activated then this sneaky little icon will show up here - language features are now available
<img width="426" alt="screen shot 2018-07-06 at 12 17 21 am" src="https://user-images.githubusercontent.com/2581815/42359780-3d63e5b6-80b2-11e8-9020-31e48f4e1d6c.png">

5. try out a language feature or two. for example to get symbol information at the cursor position:
```vim
:Veonim hover
```
<img width="398" alt="screen shot 2018-07-06 at 12 21 51 am" src="https://user-images.githubusercontent.com/2581815/42359834-afd8e4c0-80b2-11e8-84ea-a2327e872589.png">

It is possible to discover all registered Veonim commands in the cmdline if you have `wildmenu` configured to list completions:
```vim
:Veonim
```
If you have a space after `:Veonim` and press `Tab` key it should list all possible commands like so:

<img width="620" alt="screen shot 2018-07-06 at 12 34 05 am" src="https://user-images.githubusercontent.com/2581815/42360073-5da14560-80b4-11e8-879f-82aefa16c635.png">

For the future I'm thinking of a few possible enhancements to make it easier to get started with Veonim:
- start page with some common functions (open workspace, open recent, common functions, documentation, etc.)
- common menu functions (like `ctrl + shift + p` in vscode/atom/sublime) with useful Veonim functions and short descriptions (ideally it would be nice to combine this with the native vim command line)
- when opening a file that does not have a language extension installed, provide a recommendation like in vscode to install the necessary extension
- create an additional optional "full-bundle" of Veonim that comes bundled with all language server extensions and recommended vim plugins

Hope that helps!

If you have any other questions/comments/concerns let me know. Cheers!

**Comment by bfulop** [comment]
Thanks @breja for the detailed explanation and the updated documentation!

I've been playing around with Veonim and it's crazy good! I'm really impressed how far you got! All the promised features are working (that I tested). I love the workspace features (switch between workspaces and the fuzzy find). The fuzzy find is so fast to jump to the search result, at first I thought it wasn't working! I didn't realise that the left side (buffer display) was updating to the selected search result, because it just happens immediately. 😅

This is really great stuff. I may have a few questions how to further tweak Veonim now that I saw how much it can do...

For example I love the idea of transforming key events as in Karabiner. Is there a way I could remap `<space>` to CTRL but _only_ for normal mode? I have this setup with Karabiner but would be great to scope it down further. 

I saw that Veonim can also install VsCode extensions? How about this one, hahaha : https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

**Comment by breja** [comment]
Ah thanks 😃 Always happy to entertain any questions/feedback!

Key transforms do not currently support vim modes. I'm not sure why they don't, but they should. Opened #414 to track this.

Yeah, vscode extension support is still quite limited at this point in time, but hopefully one day we will be able to run vim inside a neovim :term inside veonim with vscodevim extension hah 😆
