### ISSUE TITLE
vim-polyglot breaks the language server

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#412]
Hello,

It looks like if I enable 

```
Plug 'sheerun/vim-polyglot'
```

The language server does not work for the JavaScript files. As soon as I disable it, and restart Veonim I get the ⚡️icon and the completions start working.

If I only add 

```
Plug 'pangloss/vim-javascript'
```

plugin that is used by `vim-polyglot`, the language server works.

I also tried adding

```
let g:polyglot_disabled = ['javascript', 'typescript', 'js', 'jsx']
```

to my `init.vim`, but did not help.

Finally, I tried the same with Onivim and there it doesn't seem to block the language server, only in Veonim this is why I'm posting the issue here...

EDIT: of course, these lines are outside the `if exists('veonim')` block...

**Comment by bfulop** [comment]
Thanks again for the detailed explanations !

I was just trying out Veonim with latest _master_ branch (with `npm run start:release`) and now everything seems to work with this config:

```
...
  Plug 'sheerun/vim-polyglot'
  Plug 'pangloss/vim-javascript'
...

let g:polyglot_disabled = ['javascript', 'typescript', 'js', 'jsx']
```

Maybe these settings cancel each other out and now I wouldn't need to add the disable line and the manual import of _vim-javascript_? Will test later, just too happy right now that everything is working!

If you agree with me, I let you close this issue. 👍

**Comment by breja** [comment]
Good to know that it works!

I opened a separate issue to track the underlying cause of this #417
