### ISSUE TITLE
How to get CSS completions to work?

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#416]
I tried 

```
...
  Plug 'othree/csscomplete.vim'
...
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS noci
```

and also I have

```
...
VeonimExt 'veonim/ext-css'
VeonimExt 'veonim/ext-json'
VeonimExt 'veonim/ext-html'
VeonimExt 'vscode:extension/sourcegraph.javascript-typescript'
...
```

But I'm not getting any CSS completions at all. 

Am I missing something from my settings? Should I be seeing the language server icon (⚡️) in a plain CSS file? `echo &filetype` returns `CSS` (syntax based folding also works).

**Comment by breja** [comment]
The language server icon ⚡️ should show for CSS.

This problem is because of lousy coding on my part - sorry about that. It should be fixed on `master` now.

Tech details:
Not all language servers contain completion `triggerChars` on server capabilities. The code did not handle undefined `triggerChars`. CSS lang server appears to not send `triggerChars`

**Comment by bfulop** [comment]
I tried with the latest version of the _master_ branch (`npm install` then `npm run start:release`) but Zeus has not been kind to me, still no ⚡️ for the CSS file...

(not a breaking deal for me of course, just for info. the emmet CSS completions do work)

**Comment by bfulop** [comment]
Sorry, it was my mistake! I forgot to run `npm run build` before doing `npm run start:release`! 😅

It's all working great now, I'm getting the `rebeccapurple` suggestions!

**Comment by bfulop** [comment]
Just one more thing: the lang server does not seem to start with `scss` files (reported by `echo &filetype`).

Is it a vim.init issue or something that has to fixed internally?

**Comment by bfulop** [comment]
I managed to get the CSS langserver started as per [your comment/fix for the JavaScript files](https://github.com/veonim/veonim/issues/412#issuecomment-403971237). 

I added this line to my `init.vim`

```
autocmd BufEnter *.scss set ft=css
```

The langserver support for CSS/SASS files seem to be the same: https://langserver.org.
There would not be any extra features unlocked (e.g. workspace symbols) by trying to keep the SASS filetype internally. 

I close this issue then, unless @breja figured out how to enable the langserver for SASS files.

**Comment by bfulop** [comment]
I just saw that [veonim/ext-css](https://github.com/veonim/ext-css) got updated and now the langserver does start up! 

I get a few strange (linting) errors and completions, but will report this on the extension page.

**Comment by breja** [comment]
scss/less linting errors are because the css-languageserver can not determine a languageId of `scss` or `less` so it defaults back to `css`. the reason for this was missing properties on the `textDocument/didOpen` notification message. see #426 for more info

**Comment by bfulop** [comment]
"Verified" working great ! 😉
