### ISSUE TITLE
verify viewport-search start/end ranges

### ISSUE THREAD

**Issue by davidpumpkins** [veonim/veonim#434]
in the following snippets the line numbers are adjusted by one
- w0 - 1
- w$ + 1

do we need to adjust also in viewport-search.ts? maybe that will fix the potential glitch with searching out of range?

https://www.reddit.com/r/vim/comments/8mrwu3/search_in_part_of_file/dzpwjtn
https://www.reddit.com/r/vim/comments/91g97i/search_in_the_current_screen_only/e2xsh67

**Comment by breja** [comment]
should be guuud
