### ISSUE TITLE
can we get user keymap to find out keybinds?

### ISSUE THREAD

**Issue by breja** [veonim/veonim#438]
for example, i want might want to know if the user keybound `:Veonim files` and what key it is to display visually in the GUI

also it would be good to know what keybinds are used for moving up/down so we can create custom GUI panels with the same movements as h/j/k/l - but if the user rebound them, we want to use those

**Comment by davidpumpkins** [comment]
`:h index`
`nvim_get_keymap()`

**Comment by davidpumpkins** [comment]
assume built-in commands like `hjkl` will not change. find out if user has remapped any built-in commands with `nvim_get_keymap` and use the remapped keybinds (if any) to define keybindings for custom UI panels.

e.g. swapping keys
```vim
nnoremap e j
nnoremap j e
```

**Comment by davidpumpkins** [comment]
`:h maparg()`

**Comment by breja** [comment]
yes its done
