### ISSUE TITLE
project search horizontal view? + more intelligent/customizable overlay positioning?

### ISSUE THREAD

**Issue by davidpumpkins** [veonim/veonim#441]
add an option to make project search horizontal instead of vertical? also maybe add options for TOP, LEFT, RIGHT, BOTTOM instead of default right?

something liek: `:Veonim grep view-right`

this way it can be made dynamic based on which is the current open buffer. or maybe that feature is baked in automagically? if the grep window would cover the current buffer, open it on the opposite side of the veonim window...

**Comment by breja** [comment]
not doing this. once we get `ext_windows` i want to reimplement all these kinds of widgets as normal nvim windows. at that point window management is handled by nvim
