### ISSUE TITLE
remove vn_project_root. derive statusline dir via unique dirname()

### ISSUE THREAD

**Issue by breja** [veonim/veonim#462]
if i have a `:pwd` like `/Users/a/projects/veonim` show only `veonim` in the statusline. this should work without `g:vn_project_root`. i think then we can get rid of `project.root` config.

because we use the project dir name as a default session name, we can dedup any duplicates in the session-switcher by finding the next non-duplicate parent dir ancestor.

`/Users/a/projects/one/veonim` --> `one/veonim`
`/Users/a/projects/two/veonim` --> `two/veonim`

**Comment by breja** [comment]
actually if we never set `:pwd` but we have a custom session name, should we perhaps display that in the statusline?

sometimes i will create vim sessions that only contain terminal windows. there is no interaction with `cd` and the statusline will just display `~`. i suppose it would be nice to have it display the session name instead

**Comment by bfulop** [comment]
I love this idea! 

I have some sessions too, that group files that are opened via scp or are brought in from other directories.

**Comment by breja** [comment]
Instance name now does a `basename()` on the path, so only the last dir should show in the statusline and instance switcher. `g:vn_project_root` is no longer used.
