### ISSUE TITLE
if no git installed on machine, should hide any git UI stuffs

### ISSUE THREAD

**Issue by breja** [veonim/veonim#469]
hide the branch from the statusline if there is no 'git' installed.

maybe even hide it if we're not inside a git project. only show the git branch if `:pwd` is a git project

**Comment by breja** [comment]
In that case, do you get the git branch information in the statusline?

**Comment by bfulop** [comment]
Yes currently in Veonim I have the correct branch info, even if the current dir is 5 levels deep in the GIT repo.

**Comment by breja** [comment]
Okay, that should keep working then. I think we will only hide the branch if it cannot be determined (or git is not installed on the system)

**Comment by breja** [comment]
On master: if the current `:cd` does not have a valid git status, the git segment in the statusline is hidden.
