### ISSUE TITLE
langserver rename function broken?

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#474]
I have trouble with the `:Veonim rename` (or the `sr` shortcut) feature.

It puts a `u` character and when I escape, and doesn't rename the variable. This is in a vanilla JavaScript file.

I noticed this regression a couple of days ago. I'm on the master branch and usually pull and rebuild Veonim when new commits are available.

**Comment by breja** [comment]
Sorry! Fixed in 4b0eaa00605be4d041f4315e09f0b9fe2dceffa8

**Comment by bfulop** [comment]
Great, working perfect! Thanks!
