### ISSUE TITLE
terminal title of child process if term name contains users shell

### ISSUE THREAD

**Issue by ghost** [veonim/veonim#481]
I pretty much always start my terminals in /bin/bash. Problem is that when I want to switch to a terminal buffer (like via `:Veonim buffers`) all terminal buffer names are now a variant of `/bin/bash`. It would be nice to changed the displayed name of the terminal buffer (in buffer list and window title) to the child process name.

`b:terminal_job_pid` -> get pid of terminal. If possible, we can then find the child process and get its name to display in terminal.

To get users shell:
- `finger $LOGNAME` to get the shell of the current user
- `$SHELL` variable

If the current term name contains the users default shell, we will substitute the shell name with the next child process name (if it exists).

Otherwise we can display the top process and the next child process (if it exists)

Example with my default shell of `/bin/bash`

- `:term top` -> displays `top`
- `:term` -> displays `/bin/bash`
- `:term` -> run `npm start` -> displays `npm start`
- `:term` -> run `zsh` -> run `npm start` -> displays `zsh / npm start`

https://neovim.io/doc/user/nvim_terminal_emulator.html#terminal

**Comment by breja** [comment]
Interestingly neovim has these functions in the api:

```
  getProcChildren(pid: number): Promise<any[]>,
  getProc(pid: number): Promise<any>,
```

**Comment by breja** [comment]
Getting the current process name with getProcChildren could work. However the bigger problem is having some sort of event that tells us that the title needs to be updated.

I looked into how VSCode updates the terminal title and at the time of this writing, VSCode *very* inefficiently polls. I have no interest in a polling approach. 

So now that we have buffer events and they can be attached to terminal buffers, I think we can do an update on the terminal title whenever the term buffer changes. If we do this, we should only do it for visible terminal buffers, and do a title check whenever we switch from not visible --> visible term buffer.

**Comment by breja** [comment]
Can query the current terminal process only when invoking the buffers list. Either way, low priority.
