### ISSUE TITLE
multi-query completion from langserv?

### ISSUE THREAD

**Issue by breja** [veonim/veonim#500]
So right now we only call langserv.completions ONCE on triggerChar. Sometimes this takes a long time as the langserver has to compute ALL possible completions for the given symbol (since we query when the position is at the triggerChar -> `[1,2,3].<--cursor here` triggers all array completions.

I wonder if we can improve the experience when completions take too long, by querying a second time with a more specific query. Would this be faster? Would need to somehow manage two completion responses (the full list + a more specific list). Probably would like to keep the full completion list around in case the user revises the completion query.

**Comment by chemzqm** [comment]
I don't think that would be better, language server like tsserver would always return full list of items regardless of what current query is, it's up the client to filter the complete items.
The user should be able to input more text when the completion started, and when completion is done, client could use new input to filter the complete items.

**Comment by breja** [comment]
Nothing to do here. Closing
