### ISSUE TITLE
Text search glitches

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#505]
I have the following scenario: I `cd` into a project folder and want to search for some text in the files via the `:Veonim grep` command.

I notice some unexpected behaviour, while the search results pane is open:

1. hitting the `CTRL` key changes the search results list (to my knowledge I don't have this key remapped)
2. sometimes typing in the search field also sends the key events to the currently opened buffer. I tried to search for the text _disabled_ in my SCSS files. I bring up the search panel, type in _disabled_, then hit `TAB` to scope the files and type in `css`. I then hit `Esc`, then open up the search panel again. Now, the _filter files_ field is focused so I do `Shift-TAB` to focus the `find in project` field. Now, if I type `disa` the edit happens in the open buffer.

I will try the `grep-selection` command as a workaround for now...

UPDATE: yes, using the `:Veonim grep-selection` or `grep-word` is a good workaround for the second item above.

**Comment by breja** [comment]
Some quick observations:

1. might be related to some logic about remapping cmd/ctrl -> esc? although esc should hide the UI panel... hmm
2. i've had this happen a few times. I think it's related to the tab key. Hitting tab key repeatedly causes the vim cursor to briefly flicker in the window. Since we're in an input field I'm guessing we're not `event.preventDefault` and the focus briefly changes to the next valid element (body?).

Will keep investigating.

**Comment by bfulop** [comment]
I'm using Karabiner-Elements to remap the Caps Lock key to Esc. So maybe there's some double remapping going on (by Veonim)? 
I haven't noticed any other cases where the CTRL key is doing unexpected stuff.

**Comment by breja** [comment]
33692ef88df0b406ef55481d3c7fd34302242892

**Comment by breja** [comment]
should be fixed

**Comment by breja** [comment]
Good catch on these bugs. The bugs were present in all components using inputs. Now they're fixed everywhere.

**Comment by bfulop** [comment]
Thanks, I will watch out for the langserver anomalies! 

I've been using Veonim now full time for the last three or four months, and from the end-user's perspective the quality is great especially for a "pre-alpha" release! ✨
