### ISSUE TITLE
integrate change-dir with 'cd|lcd' in cmd palette

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#51]
look and do like mada "query" pre selector

**Comment by deomitrus** [comment]
deprecate change-dir and instead create "shortcut" to preload cmd palette with *cd*

**Comment by deomitrus** [comment]
do we reaaaallly need this integrated? vim comes with it's own cd/e functionality. maybe just expose wildmenu options in command plugin

**Comment by goavn** [comment]
no
