### ISSUE TITLE
typescript-langserv completions no content available spammy error in console

### ISSUE THREAD

**Issue by breja** [veonim/veonim#520]
why does this happen? is it related to incremental updates? does it have anything to do with neovims spammy buffer notifications on completion?

<img width="493" alt="screen shot 2018-10-07 at 10 10 39 pm" src="https://user-images.githubusercontent.com/2581815/46590033-275e9480-ca7e-11e8-9005-17111fb0b289.png">

**Comment by chemzqm** [comment]
It's possible that the buffer is detached by `:edit` or `:checktime` and veonim lost trach of the buffer change events.

**Comment by breja** [comment]
Thanks for the hint. I'll take a look at the logic around `:edit` and `:checktime`

**Comment by chemzqm** [comment]
I think this is bug of tsserver, it throw this error whenever no complete item found for completion.

**Comment by chemzqm** [comment]
The command `completionInfo` of tsserver (added in v3.0.0) throw this error when complete a new symbol like: `let fo|`, the old command `completions` return global symbols.

**Comment by breja** [comment]
Closing issue as no longer relevant. We are now using VSCode extensions which abstract the language server integration.

Thanks @chemzqm for the insights and inspiration on integrating VSCode extensions. For anyone lurking in here I'd recommend checking out https://github.com/neoclide/coc.nvim it's awesome.
