### ISSUE TITLE
How about remapping <C-z>?

### ISSUE THREAD

**Issue by bfulop** [veonim/veonim#534]
I'm relatively new Vim user and so just recently discovered that `<C-z>` takes you to the terminal (and `fg` will take you back to Vim).

This of course has no meaning in Veonim (afaik), and each time I accidentally hit `<C-z>`, I thought I crashed the app, and had to restart it. 

So maybe it would be a good idea to suggest in the docs to remap `<C-z>` for other beginner users?

**Comment by breja** [comment]
Definitely agree. I have remaped `<c-z>` to `<nop>` in the nvim startup script. A user can remap (or unmap) the binding afterwards in their init.vim.

**Comment by bfulop** [comment]
Great thanks for the fix!
