### ISSUE TITLE
question: how to install plugin

### ISSUE THREAD

**Issue by iamcco** [veonim/veonim#539]
i have add `quick start copypasta config` to my config, but nothing happen when open veonim, is missing something ?

**Comment by breja** [comment]
Sorry, I'm not sure what you're trying to do and what you're expecting to happen? I admit the user-friendliness for Veonim is lacking at this point in time. There is future work that will improve the UX for that.

According to your title, you are wondering how to install a vim plugin to Veonim?

For a vim plugin, after you add `Plug 'some/repo'` to init.vim, you should see a notification that says that plugins are being downloaded and installed. Afterwards the workflow is identical to a vim workflow.

For a Veonim extension, the behavior is similar. You add `VeonimExt 'some/repo'` to init.vim and you should see a similar notification
<img width="398" alt="downloadinglol" src="https://user-images.githubusercontent.com/2581815/48161547-d4f4db80-e2a8-11e8-98fb-6b0953c01ce7.png">

The download/install steps only happen if a plugin and/or extension has not yet been downloaded before. If something went wrong, a notification should indicate that - and more info might be available in the dev tools console (there is future work to improve the UX in this process).

If everything was successful, you can start using supported language features. For example a workflow is something like:

- open project folder: `:cd ~/path/to/project`
- fuzzy open a file: `:Veonim files`
- use language server features like symbols list: `:Veonim symbols`
- etc.

Did I answer your question?

**Comment by iamcco** [comment]
i have add this config in my init.vim, but i can't get the notification

```viml
" built-in plugin manager
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'

" extensions for web dev
VeonimExt 'veonim/ext-css'
VeonimExt 'veonim/ext-json'
VeonimExt 'veonim/ext-html'
VeonimExt 'vscode:extension/sourcegraph.javascript-typescript'

" workspace management
let g:vn_project_root = '~/proj'
nno <silent> <c-t>p :call Veonim('vim-create-dir', g:vn_project_root)<cr>
nno <silent> ,r :call Veonim('change-dir', g:vn_project_root)<cr>

" multiplexed vim instance management
nno <silent> <c-t>c :Veonim vim-create<cr>
nno <silent> <c-g> :Veonim vim-switch<cr>
nno <silent> <c-t>, :Veonim vim-rename<cr>

" workspace functions
nno <silent> ,f :Veonim files<cr>
nno <silent> ,e :Veonim explorer<cr>
nno <silent> ,b :Veonim buffers<cr>
nno <silent> ,d :Veonim change-dir<cr>

" searching text
nno <silent> <space>fw :Veonim grep-word<cr>
vno <silent> <space>fw :Veonim grep-selection<cr>
nno <silent> <space>fa :Veonim grep<cr>
nno <silent> <space>ff :Veonim grep-resume<cr>
nno <silent> <space>fb :Veonim buffer-search<cr>

" color picker
nno <silent> sc :Veonim pick-color<cr>

" language server functions
nno <silent> sr :Veonim rename<cr>
nno <silent> sd :Veonim definition<cr>
nno <silent> st :Veonim type-definition<cr>
nno <silent> si :Veonim implementation<cr>
nno <silent> sf :Veonim references<cr>
nno <silent> sh :Veonim hover<cr>
nno <silent> sl :Veonim symbols<cr>
nno <silent> so :Veonim workspace-symbols<cr>
nno <silent> sq :Veonim code-action<cr>
nno <silent> sp :Veonim show-problem<cr>
nno <silent> sk :Veonim highlight<cr>
nno <silent> sK :Veonim highlight-clear<cr>
nno <silent> <c-n> :Veonim next-problem<cr>
nno <silent> <c-p> :Veonim prev-problem<cr>
nno <silent> ,n :Veonim next-usage<cr>
nno <silent> ,p :Veonim prev-usage<cr>
nno <silent> <space>pt :Veonim problems-toggle<cr>
nno <silent> <space>pf :Veonim problems-focus<cr>
nno <silent> <d-o> :Veonim buffer-prev<cr>
nno <silent> <d-i> :Veonim buffer-next<cr>
```

**Comment by breja** [comment]
Thanks for sharing the logs.

It looks like you have the `VeonimExt` commands inside a different file than `init.vim`. I'm guessing this is sourced from `init.vim`?

Currently Veonim regex parses the `Plug` and `VeonimExt` commands from init.vim to download plugins and extensions. Obviously this is not the right solution - we should be able to support commands even in sourced files.

If you want you could try moving the `VeonimExt` commands to `init.vim` as a temporary measure to see if it makes any difference.

I have opened #544 to track the support of proper veonim commands that work in sourced files.

**Comment by iamcco** [comment]
it seems same error when move to init.vim (init.vim is link which is .config/nvim/init.vim link to my config):
![image](https://user-images.githubusercontent.com/5492542/48482799-9e8d0280-e84c-11e8-9581-95bf985efd41.png)
