### ISSUE TITLE
buffer :Veonim calls on startup

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#54]
because by the time plugins and action listeners are bound the call could be missed.

check transport level logs to see if we catch :Veonim cmd. could be that by the time `subscribe` is called, it's too late.

also, does it make a difference if we call `subscribe` before `ui_attach`?

**Comment by goavn** [comment]
--idea--

set flag with--cmd
```g:veonim_loaded = 0```

update :Veonim cmd
```viml
if g:veonim_loaded | rpcnotify(0, 'veonim', <f-args> | else | call timer_start(1, {-> rpcnotify(0, 'veonim', <f-args>} | endif
```

once loaded set loaded true
```api.command('let g:veonim_loaded=1')```
