### ISSUE TITLE
Some messages never close

### ISSUE THREAD

**Issue by josemarluedke** [veonim/veonim#546]
I have noticed that some messages never close. They get pushed if new messages come in, but the last few messages never disappear.

![screen shot 2018-11-20 at 4 56 26 pm](https://user-images.githubusercontent.com/230476/48812085-85210600-ece5-11e8-8d3f-9326ef2396fd.png)

While, some messages that should be kept, they disappear very fast. Example: When using neerd tree, after executing `m` to show menu, it shows the menu but it closes right after.

**Comment by breja** [comment]
Messages not being cleared should be fixed in [0.13.2](https://github.com/veonim/veonim/releases/tag/0.13.2). I have also added a command to clear all messages: `:Veonim messages-clear`
