### ISSUE TITLE
Can't run veonim on win10

### ISSUE THREAD

**Issue by kdurant** [veonim/veonim#549]
Can't do anything after open veonim .exe

**Comment by skt041959** [comment]
I have tried with 0.13.3-win.zip release, and test it with your example init.vim.

The veonim window shows, but won't redraw the buffer. If I input some characters, the cursor position at below right corner will response, but I can't see anything in the buffer.

**Comment by breja** [comment]
Okay, Windows 10 builds should be working now. External messages are not yet supported. I opened #556 to address that.

Let me know if veonim works on windows for you

**Comment by kdurant** [comment]
The file can be opened, but any operation may cause the veonim to become unresponsive

**Comment by breja** [comment]
I'm not sure if this still applicable in 0.22.0?

It's been a while since this issue has been active. I'm going through cleaning the issue backlog and closing resolved and/or inactive issues. Please reopen if you still have questions or just want to post some funny memes.
