### ISSUE TITLE
Can you or someone make an AUR package of veonim?

### ISSUE THREAD

**Issue by Kazimazi** [veonim/veonim#554]

**Comment by breja** [comment]
I'm not really familiar with the process of creating AUR packages. I can add it to my list of things to explore. If anyone else has a head-start on this process, I would appreciate the input.

**Comment by breja** [comment]
AUR package here: https://aur.archlinux.org/packages/veonim

Big thanks to @richin13 for setting this up!

**Comment by richin13** [comment]
Glad to help
