### ISSUE TITLE
Cannot set font

### ISSUE THREAD

**Issue by khalidchawtany** [veonim/veonim#559]
As per guides I set the g:vn_font variables. However, nothing happens.

I am on OS X running the latest version of veonim

**Comment by khalidchawtany** [comment]
It seems that the font is hard coded.
https://github.com/veonim/veonim/blob/eb99eef3c35716b7185ded3c75320eba7dd5d200/src/bootstrap/index.html#L6-L20

**Comment by breja** [comment]
Do you see any errors in the console?

I set the following settings in `init.vim` and restarted Veonim

```vim
let g:vn_font = 'Comic Sans MS'
let g:vn_font_size = 16
```

<img width="882" alt="screen shot 2018-12-28 at 16 39 00" src="https://user-images.githubusercontent.com/2581815/50528936-5dc91000-0abf-11e9-8a2d-7a1da7962655.png">

In the next major version Veonim will support `guifont` and hot reloading the font.

**Comment by breja** [comment]
Ah yes, sorry about that - I should document that. For performance reasons veonim regex parses the font variables from init.vim file text. This hackery will go away once we use the standard `guifont` option.
