### ISSUE TITLE
Empty window on macOS Mojave

### ISSUE THREAD

**Issue by appelgriebsch** [veonim/veonim#561]
Using your latest release and the sample configuration shown in the user guide on macOS Mojave results in an empty screen with no way to open files or folders. I checked the dev tools console log, but no errors or warnings stated there. Any idea?

<img width="948" alt="screenshot 2019-01-01 at 12 40 45" src="https://user-images.githubusercontent.com/6803419/50572528-f1058c80-0dc2-11e9-9a66-13afd9d1dbb9.png">

**Comment by appelgriebsch** [comment]
Looks like the bundled Neovim binary throws an error
```bash
./node_modules/\@veonim/neovim-mac/bin/nvim
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /xxxxxxx/veonim/./node_modules/@veonim/neovim-mac/bin/nvim
  Reason: image not found
Abort trap: 6
```

**Comment by appelgriebsch** [comment]
This missing library seems to be the issue. Just created a symbolic link to an existing libintl.8.dylib on my Mac to the above mentioned location within /usr/local/opt (homebrew?) and afterwards the client boots up successfully. Would be good to bundle the library in the app package if it is really needed.

**Comment by breja** [comment]
Hmm, interesting. Do you have `nvim` installed anywhere else on the system? Perhaps the bundled nvim is looking at the wrong paths.

**Comment by appelgriebsch** [comment]
Nope, I refer to the one bundled with veonim...
```bash
otool -L /Applications/veonim.app/Contents/Resources/app/node_modules/\@veonim/neovim-mac/bin/nvim
/Applications/veonim.app/Contents/Resources/app/node_modules/@veonim/neovim-mac/bin/nvim:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.23.0)
        **/usr/local/opt/gettext/lib/libintl.8.dylib** (compatibility version 10.0.0, current version 10.5.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
        /usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by breja** [comment]
Well I'm perplexed. I would expect the missing library to be provided by nvim. My only guess would be that I messed up building neovim (likely). I wonder if an official neovim binary is missing the lib.

I do have veonim on two Mojave machines without issues, but maybe I picked up the missing lib from somewhere else (some homebrew install? xcode command line tools? 🤷‍♂️ )

**Comment by appelgriebsch** [comment]
I've just downloaded an official binary package from Neovim for macOS and checked the content...

```bash
ls
bin     libs    share
```

so it has a dedicated libs directory as part of the package. This contains the following files:

```bash
ls libs/
libiconv.2.dylib        libintl.8.dylib         libutil.dylib
```

and the binary is linked to them:

```bash
otool -L bin/nvim
bin/nvim:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
        @executable_path/../libs/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
        @executable_path/../libs/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
        @executable_path/../libs/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Btw: why do you compile Neovim on your own? Wouldn't it be easier and safer to just use their latest binary packages?

**Comment by appelgriebsch** [comment]
Another finding: if I do a nvim --version in the veonim app bundle it shows me that the bundled version is still on 0.3.1 (on macOS), and you can also see that in the compiler settings it lists an include path to /usr/local/opt/gettext...

```bash
./bin/nvim --version
NVIM v0.3.1-41-gc84f58826
Build type: Release
LuaJIT 2.0.5
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS-I/Users/a/proj/nvsrc/build/config -I/Users/a/proj/nvsrc/src -I/Users/a/proj/nvsrc/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/a/proj/nvsrc/build/src/nvim/auto -I/Users/a/proj/nvsrc/build/include
Compiled by a@a

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by breja** [comment]
It's been a while since this issue was active. As of 0.22.0 Veonim now uses the official Neovim provided binaries. I expect this resolves some of these issues?

I'm going through cleaning the issue backlog and closing resolved and/or inactive issues. Please reopen if you still have issues or just want to post some funny memes.
