### ISSUE TITLE
Rust language server throws an exception

### ISSUE THREAD

**Issue by appelgriebsch** [veonim/veonim#563]
Based on your ext-go extension I created an ext-rust extension (https://github.com/appelgriebsch/veonim-ext-rust) that will trigger and spawn the rust language server (rls).

This works ok, but the rls will send an exception upon first interaction about a malformed message being received (expect a sequence, retrieved a map).

Might have to do with the langserver integration, isn’t it?

**Comment by breja** [comment]
Sorry about that - I fixed the `initalize` and `initialized` notifications to be according to the LSP spec.

Completions from RLS:
<img width="275" alt="screen shot 2019-01-01 at 20 37 11" src="https://user-images.githubusercontent.com/2581815/50578315-5464de00-0e06-11e9-9549-fa832d0efa8a.png">

Awesome work on putting together a Rust extension!

**Comment by appelgriebsch** [comment]
Just tried your new version. Works. Very cool job, thx!
