### ISSUE TITLE
Configurability of GUI elements

### ISSUE THREAD

**Issue by clason** [veonim/veonim#566]
It would be nice if the error message popup could be configured regarding 
1. placement (I prefer the bottom right over the top center)
2. timeout (the current timeout is a bit too short for me, especially if a plugin spams several status updates in short succession).

Similarly, an option to have the command line at the top rather than the center (and maybe a bit smaller) would be nice since it currently can get in the way with `inccommand`.

**Comment by shaform** [comment]
I also feel that the popup is kind of annoying at the current state. It's too hard to read the linting error messages with the current timeout. And navigating through the source code also produces a lot of popup messages.

**Comment by breja** [comment]
The notifications are garbage. I'm going to rework them to be more tolerable. The neovim `ext_messages` feature was not really ready for prime time when I started the work on notifications. `ext_messages` is much better now and I will be working on this as soon as I finish implementing the new external multigrid UI.

**Comment by breja** [comment]
The messages have been completely reworked in 0.22.0 with the addition of `ext_messages` in Neovim. There are still a few rough edges (e.g. #612) but should generally be a better experience.

The cmdline position is a bit tricky but I opened #571 to address that.

If you still feel the message popup position should be configurable, please reopen the issue. I felt that doing what VSCode does (bottom right) should feel most familiar.
