### ISSUE TITLE
Use with standard vim plugins

### ISSUE THREAD

**Issue by clason** [veonim/veonim#567]
(I know that this is not the primary goal of this project, but I'm interested in using veonim as a cross-platform (macOS/Linux) neovim GUI. If this is not even a secondary goal, feel free to close this issue as `wont-fix`. Also, sorry for spamming multiple issues.)

Veonim seems to have some incompatibilities with vim plugins:

1. I can't get omnicomplete working with `lervag/vimtex`: pressing `ctrl-x ctrl-o` leads to a brief change in the status bar, but no menu pops up.
2. For the same plugin, `<localleader>` commands only get executed after a delay of about a second.
3. I don't get autocompletions from `ncm2`; I only see suggestions from the current buffer (presumably from veonim's own autocompletion).
4. I don't get git indicators in the status bar even when I'm editing files in a git repository.

I know this is little information to go on; I'd be happy to add more information if you tell me how to debug this with veonim. Is it possible to disable some or all of veonim's builtin extensions to test whether this is a conflict?

**Comment by clason** [comment]
1. and 3. makes sense (and is all that is needed for my purpose).

2. The commands are still executed, but with a delay, so it's not that. I'll have to investigate how to reproduce this more consistently (and measurably). Is there any way to profile veonim itself to see if the commands are just passed with a delay or whether there's actually a delay in executing them (or showing the results)?

4. Yes, but I also have `git` from homebrew. I'll try reinstalling to see if that changes things.

**Comment by breja** [comment]
It's possible to profile veonim with the DevTools: `:Veonim devtools` (I believe it should also be available from the Help menu)

On the performance tab you can record a profile:
<img width="477" alt="screen shot 2019-01-03 at 08 33 14" src="https://user-images.githubusercontent.com/2581815/50640563-3c3ead00-0f33-11e9-80de-816c327fc734.png">

I would look for KeyDown input events. As you can see veonim does very little processing on the input with the event handler - on average the sending of input to neovim takes around ~1ms (there is probably some room for improvement here). Depending on the type of input, veonim waits around ~2ms for neovim to do some real work. It then takes around ~5-15ms to to paint the screen. This painting part has been heavily optimized on the webgl branch and takes less than a millisecond for most render events.

<img width="658" alt="screen shot 2019-01-03 at 08 37 01" src="https://user-images.githubusercontent.com/2581815/50640573-42348e00-0f33-11e9-82f7-4b89576ffa2e.png">

_development build profile captured on 1.2ghz core m3 CPU on battery power_

**Comment by clason** [comment]
Thanks! That will take me a while to interpret. There's certainly some delay compared to VimR (but less than a second on this machine), and messages get queued weirdly, but there's nothing obvious from the profiler. (Just for reference, these are commands that trigger external tools and don't change the buffer, so no repainting should be necessary.) Probably nothing to worry about at this point; I'll see if I can get something more reproducible (without the whole TeX stack).

**Comment by breja** [comment]
Veonim autocomplete can now be disabled by overriding the `completefunc` in the vimrc. This should fix issues 1 and 3.

I am opening #642 to track the git issue.

I'm going through cleaning the issue backlog and closing resolved and/or inactive issues. Please reopen if you still have questions or just want to post some funny memes.
