### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by appelgriebsch** [veonim/veonim#568]
Any plans to have a sponsorship via OpenCollective or Patreon?

**Comment by breja** [comment]
No plans.

Veonim depends heavily on Neovim, especially the on-going work on externalizing the UI. I personally donate to Neovim and if anyone else is interested: https://salt.bountysource.com/teams/neovim

Some things on the roadmap for external UI that I'm excited about:
https://github.com/neovim/neovim/issues/9421

There is also Oni who are working on a native rewrite that seems pretty interesting:
https://www.patreon.com/onivim

**Comment by clason** [comment]
> There is also Oni who are working on a native rewrite that seems pretty interesting:
https://www.patreon.com/onivim

You mean https://github.com/onivim/oni2?

**Comment by breja** [comment]
Yeah. I should have specified "if anyone is interesting in donating to fund Oni2" and put both links.
