### ISSUE TITLE
windows fail to download/install plugins/extensions

### ISSUE THREAD

**Issue by breja** [veonim/veonim#569]
it's so hard to test the windows builds since i don't have a windows machine...

- check that the appropriate plugin/extension destination folders are created successfully
- check that the http downloader is working
- check that the unzip util is working

**Comment by appelgriebsch** [comment]
I can help with testing Windows builds. My office laptop runs Windows 10.

**Comment by breja** [comment]
@appelgriebsch I appreciate your offer to help with testing. The extension strategy has completely changed with VSCode extensions, so I don't think this issue is still relevant. But we will make sure VSCode extensions are being installed properly on all platforms.
