### ISSUE TITLE
Light colorscheme

### ISSUE THREAD

**Issue by goerz** [veonim/veonim#576]
How can I switch the app to a light colorscheme?

**Comment by appelgriebsch** [comment]
You can add a light Vim theme to the init.vim file in ~/.config/nvim such as ayu-vim:

```vimrc
Plug 'ayu-theme/ayu-vim'

let ayucolor="light"  " for light version of theme
" let ayucolor="mirage" " for mirage version of theme
" let ayucolor="dark"   " for dark version of theme
colorscheme ayu
```

**Comment by goerz** [comment]
Well, that sort of works, except that `ayu-vim` isn't my colorscheme (
https://github.com/goerz/vimrc/blob/17f67b6f85a0c5c5c7370b86426d4ff68894fba0/colors/goerz.vim). Also, tab titles and the command popup are pretty unreadable. It would be much preferable if veonim behaved like my terminal, where I can set the UI colors for the terminal emulator, and then load my colorscheme in vim. Is there any way to detect that I'm running in veonim (like `has:veonim`)? I just don't know what's up with every Electron app thinking that a dark UI scheme is a good default, when every other window on my operating system is light.

**Comment by appelgriebsch** [comment]
Please check out the user guide here: https://github.com/veonim/veonim/blob/master/docs/readme.md

There is a section how to check if you’re running in Veonim in your init.vim.

Also note that the original author has clearly stated that this whole project is still in the beginning and very early alpha, so things are not set in stone (yet)

**Comment by breja** [comment]
I don't think it's possible to have a default color scheme that everyone will like. So the default color scheme is mostly related to branding and the fact that Neovim has `background=dark` as a default. Users can change the `colorscheme` as they desire, and Veonim should support work well with various color schemes.

This issue has been inactive for some time. I'm going through cleaning the issue backlog and closing resolved and/or inactive issues. Please reopen if you still have questions or just want to post some funny memes.
