### ISSUE TITLE
Errors at starttup

### ISSUE THREAD

**Issue by khalidchawtany** [veonim/veonim#581]
I am sorry for asking lots of questions :), but I don't know how to contact you by any other means.

When I issue `:messages` nothing happens. Even using the redir trick to capture the messages captures nothing.

Another issue is that I get some errors at startup. I know **Veonim** is a work in progress, but it is already a great gui 👍 

![screen shot 2019-01-09 at 10 01 33 am](https://user-images.githubusercontent.com/1681606/50882395-b5d41080-13f5-11e9-9dc2-edc9874d40dd.png)

**Comment by breja** [comment]
No worries about the questions. 😃 

Maybe I could start a discord server for less formal questions/chat. Not sure if there is any interest in that.

`:messages` is not yet implemented in the UI. It does log to the devtools console though.

I've never seen those other errors before. I looked up 'E12' error and seems to have something to do with the `secure` option. As far as a I'm aware veonim does not do anything with the `secure` option.

Is there a init.vim file being loaded?

If you want to get your hands dirty you could try commenting out the `SourcePre` autocmd in the veonim startup and see if it makes any difference.

This line:
https://github.com/veonim/veonim/blob/2bde07cb7dcbf3288648e156dbbf7c98bfe8404f/src/neovim/startup.ts#L79

**Comment by khalidchawtany** [comment]
Thanks for the replies. Commenting out the `SourcePre` did the trick. I see no more errors at startup.
Is it required? Forgive my ignorance. What would be the impact of not having it?

**Comment by breja** [comment]
It was an attempt to try to detect when the user changed their vimrc and any other sourced files, but it didn't really work. I think I will remove it.

**Comment by khalidchawtany** [comment]
@breja  thanks the errors part is fixed.
I hope the messages part get fixed soon :)

Thanks for your effort.
