### ISSUE TITLE
follow up on invalid `win_pos` events on `ext_multigrid`

### ISSUE THREAD

**Issue by breja** [veonim/veonim#585]
a few observations:

behavior 1: multiple "win_pos" events reported with the same row,col (e.g. 0,0)
behavior 2: receive "grid_resize" events (gridId > 1) but no followup "win_pos" events

i made the assumption that a grid_resize event was always going to follow up
with a win_pos event. i think however there are grids that never get
positioned, so we need to make sure they do not get rendered

we also have win_pos events that overlap on the same start_col,start_row indexes
this should not happen on ext_multigrid, maybe floating windows but not here

---

behavior 2: i coded a work around for. it's a bit annoying since at the end of each redraw event we have to go back and cleanup any invalid grids

behavior 1: tried a fix, but it failed miserably. i think we have to dedup inside the `win_pos` event for multiple windows with the same row/col positions.

i haven't been able to reproduce this, so i'm not sure if the bug is in my code or neovim. bfredl recommended opening a issue after mentioning it in gitter

- [ ] open issue with neovim
- [ ] attempt a fix for behavior 1 inside the `win_pos` event?

**Comment by bfredl** [comment]
Is this easy to reproduce i e with some sequence of wincmds?

**Comment by bfredl** [comment]
> I believe it is my burden to prove if the behavior is in Neovim - right now it could just be my lousy code.

Bad input shouldn't cause nvim to get into a self-inconsistent state. Even if veonim did an invalid request, the result should be an error or silently ignored, but the nvim window layout must remain valid. So this is still a nvim bug.

**Comment by bfredl** [comment]
@breja I might have identified the issue. Nvim does not manage the size of terminal windows correctly in multigrid mode. Though I don't see the flow to invalid positions yet, I will investigate more soon.

**Comment by bfredl** [comment]
@breja some bugs surrounding multigrid + `:terminal` were fixed in nvim. Is this still an issue?

**Comment by breja** [comment]
@bfredl Thanks for the follow up - sorry I did not create an issue on the neovim repo. I have been using nightly neovim builds for the last day or so. Thus far I am not seeing any issues with invalid `win_pos` events. I'll keep an eye out for just a bit longer, but I think we might be good.

Thanks for the fix and proactiveness on the issue. I know sometimes open source can be a thankless project so I want to give credit where it's due. 👍

**Comment by breja** [comment]
I'm not seeing any issues with invalid `win_pos` events in `:terminal`. Closing issue. Thanks @bfredl!
