### ISSUE TITLE
custom nvim.init

### ISSUE THREAD

**Issue by ovidius72** [veonim/veonim#599]
Is it possible to force veonim to load a custom config file ?
When I run it and it load the default nvim.init file, it seems that most of the plugins and mappings are broken (coc.vim in my case doesn't work).
It would be nice if veonim could be load a specific config file without  the risk to have conflict with the default one.
Thanks

**Comment by khalidchawtany** [comment]
You could add a custom file to source only if Veonim is running.
Put this on top of your init.vim
```
if exists('veonim')
   source ~/.config/nvim/veonim.vim
   finish
endif
```

**Comment by ovidius72** [comment]
@khalidchawtany Thanks. I saw this in the documentation and I've tried to use that way. 
But what if I want exclude veonim to load the other configurations on the init file ?
Probably one could negate the condition, but if you use other neovim gui such as vimr or oni you will end up with a mess of conditional rules.

**Comment by khalidchawtany** [comment]
I have set up my config as shown below. I source each file in the init/ directory from the init.vim.
I have a file for each gui (for example veonim) I want to try out and put this on top of it:
```
if !exists('veonim')
    finish
endif

```
![Screen Shot 2019-03-18 at 11 12 37 PM](https://user-images.githubusercontent.com/1681606/54560401-58e76e80-49d3-11e9-89d5-497e7a0f0104.png)

**Comment by breja** [comment]
Another way could be to set the `XDG_CONFIG_HOME` or `MYVIMRC` environment variables before starting the app (in a shell or script).

Something like:
```shell
#!/bin/bash
MYVIMRC=~/.config/test_veonim/init.vim
./veonim
```

There is also the nvim `-u` command line argument, but it is not exposed to veonim. That could change if there's interest.

**Comment by ovidius72** [comment]
@khalidchawtany That sounds interesting. I'll definitely give it a try. 
One thing I still don't understand: How do you skip loading configuration that are only for neovim ? 
E.g I want vim.con  in neovim but i don't want it to bel loaded in veonim
Thanks

**Comment by ovidius72** [comment]
Ah, maybe I need to wrap neovim specific configuration in `if exists('nvim')` ?

**Comment by janek** [comment]
I believe so, this is what the [example config](https://github.com/veonim/veonim/blob/master/docs/readme.md) shows

**Comment by breja** [comment]
I'm not sure if the issue is resolved or not? I'm going through cleaning the issue backlog and closing resolved and/or inactive issues. Please reopen if you still have questions or just want to post some funny memes.
