### ISSUE TITLE
Seraching using / does not give any feedback

### ISSUE THREAD

**Issue by khalidchawtany** [veonim/veonim#601]
When searching using / there is no prompt visible. The text that you type is indeed searched for. However, it is very inconvenient that you don't see what you have typed.

![veonim_search_issue](https://user-images.githubusercontent.com/1681606/54613507-df4f8f00-4a6b-11e9-9fb6-99d2dd01c494.gif)

**Comment by breja** [comment]
Hmm, well I'm perplexed. I can't reproduce the issue? 

This is what I do:
`/no`

<img width="269" alt="Screen Shot 2019-03-19 at 20 16 26" src="https://user-images.githubusercontent.com/2581815/54650396-9526d780-4a84-11e9-8028-177dd748fd87.png">

And then either "forward search" or "backward search" pops up.

Gonna need to think about how this could happen...

**Comment by khalidchawtany** [comment]
This happens when / is remapped. If I unmap it, the problem goes away.

**Comment by breja** [comment]
Can you give an example of a remapping you tried?

**Comment by khalidchawtany** [comment]
I use `junegunn/vim-oblique` plugin.
My mappings are 
```
  nmap /  <Plug>(Oblique-/)
  omap /  <Plug>(Oblique-/)
  xmap /  <Plug>(Oblique-/)
```
I have remapped all of ` #, *, /, ?, g#, g*, z/, z?` the same way. Except that some of them does not have `omap`.
