### ISSUE TITLE
Veonim files prompt window keys are not remapped

### ISSUE THREAD

**Issue by khalidchawtany** [veonim/veonim#603]
The command prompt window keys are correctly remapped according to neovim. However, other prompt window keys are not remapped.

![veonim_files](https://user-images.githubusercontent.com/1681606/54615193-b7adf600-4a6e-11e9-9d70-0606ba21ffd1.gif)

**Comment by breja** [comment]
Yes, command and "forward search"/"backward search" inputs are controlled by neovim. Other inputs are controlled by veonim. I would prefer to use the same neovim input mappings everywhere.

How to achieve neovim controlled inputs everywhere is a bit of a mystery to me. Maybe there is a way to ask neovim for all command line built-in and user-defined mappings (and then figure out how to translate that to input actions). Or maybe we can hack something on top of `input()`.

Will need to think on this. Not a quick fix unfortunately.

**Comment by breja** [comment]
I also find this annoying. I figured out how to use neovim controlled inputs everywhere. This will definitely happen in the Great Big Rewrite of 2020.
