### ISSUE TITLE
Support for native pasteboard

### ISSUE THREAD

**Issue by mlhetland** [veonim/veonim#606]
It would probably be useful to be able to copy things to the native pasteboard (either with the yank commands, or by native keyboard combos), but pasting certainly seems quite natural. There's even config in the README seemingly meant to be copied into `init.vim`, but for now, you'd either have to save the source from the browser (or using `curl` or something) and edit that, or paste into a different editor.

**Comment by mlhetland** [comment]
Not sure what shortcut `“+p` is – I manated to get cmd-p to work as a normal yank, but that still just pastes from veonim's own pasteboard. Are you able to paste stuff you've copied from elsewhere?

**Comment by khalidchawtany** [comment]
“+p pastes from system clipboard. “[register]p pastes the content of the [register] and the [+] register happens to be the clipboard. [:help registers] for more info.

**Comment by mlhetland** [comment]
Aah, right!-D
