### ISSUE TITLE
Python support?

### ISSUE THREAD

**Issue by matteha** [veonim/veonim#609]
Very exciting. Is there support for Python? I tried ms.python but couldnt get it to work, seems like the Python language server / VS Studio extension didn't start.

Thanks

**Comment by breja** [comment]
I will look into it.

**Comment by TalAmuyal** [comment]
I tried that too.
I get to following message when opening a `.py` file:

```
invoking PipEnv Error: spawn pipenv ENOENT
...
Python Extension: Relevant Environment Variables {
    "PATH": "/usr/bin:/bin:/usr/sbin:/sbin"
}
```

While `which pipenv` gets me: `/usr/local/bin/pipenv`.
Which means that:
A) `pipenv` is required.
B) `pipenv` is not found even when installed.

Tried to fix it by adding `let $PATH .= ':/usr/local/bin'` to my init.vim, but to no avail :( (the `PATH` env in the error mesage stays the same).

Any tips?

**Comment by TalAmuyal** [comment]
Forgot to mention that I use the pre-release of 0.22.0.

**Comment by matteha** [comment]
For Python, I have this in the the init.vim:

let g:vscode_extensions = [
  \'ms-python.python',
\]

But it doesn't use the VS Studio Extension or launch the Microsoft Python Language Server in the background. It does work on regular nvim.

**Comment by TalAmuyal** [comment]
What do you mean by "It does work on regular nvim"?

**Comment by matteha** [comment]
The Microsoft Python Language Server works for autocomplete on the regular nvim, but it requires some hacking and plugins unfortunately, whereas it should natively work in veonim. Hopefully this could be fixed, would be great!

**Comment by breja** [comment]
The built-in extension host was never 100% compatible with all vscode extensions. By this point the built-in extension host has fallen very far behind in compatibility with the vscode API. The current approach is flawed and as such vscode extension support will be deprecated/removed.

There is new experimental work being done on [Tirion](https://github.com/veonim/tirion) which will instead attempt to create a bridge between Neovim and the Code Extension host without emulation. If that experiment is successful it will be integrated in Veonim.
