### ISSUE TITLE
None of the :Veonim commands do anything on Windows

### ISSUE THREAD

**Issue by JaniM** [veonim/veonim#610]
Executing eg `:Veonim explorer` just fails silently. In fact I did some testing and as long as there is an argument, nothing happens. `:Veonim asd` behaves the same.

If no argument is given, I get "E471: Argument required".

**Comment by breja** [comment]
Okay, I will investigate.

**Comment by JaniM** [comment]
I downloaded 0.14.0 out of curiosity. It works as expected.

**Comment by zakkor** [comment]
Same issue here on Windows 10

**Comment by kenny-evitt** [comment]
I'm seeing this in 0.22.0. Anything I can do to help? I'll try to setup a dev environment first.

**Comment by breja** [comment]
I don't have Windows OS so I can't help. There have been some other Windows related fixes contributed by others. Maybe those fixed this.
