### ISSUE TITLE
Font ligatures support

### ISSUE THREAD

**Issue by beanaroo** [veonim/veonim#611]
I have tried a few fonts and none appear to be rendered with ligatures. An example would be [Fira Code](https://github.com/tonsky/FiraCode)

I'm not sure how complex this would be but thought it be worth tracking :)

**Comment by breja** [comment]
Yeah, currently not supported. It's fairly complex (at least to me) to implement and I'm worried it would slow down rendering.

Probably low priority item for now. Like for example, I think debug adapter support is more interesting than ligatures. I am however open if someone else wants to take a crack at it.

**Comment by breja** [comment]
This is currently out of scope. There is some upcoming work that might bring about ligatures support. We will see.
