### ISSUE TITLE
Can't Dismiss Notifications

### ISSUE THREAD

**Issue by barakmich** [veonim/veonim#612]
OS: Ubuntu 18.04 LTS
Version: 0.22.0.AppImage

I like the general feel, and was able to add vscode extensions to my .vimrc (which has a lot of configurations and a long history that mostly works)

The plugins successfully install and I see "(Dismiss / CSN)" -- but I've tried all the key combinations (c, s, n, Ctrl-Shift-N) and I can't seem to get it to disappear. 

Is there a Veonim command for this? Or a key binding I'm missing?

**Comment by teevans** [comment]
Also have this same issue.

**Comment by JaniM** [comment]
Does not appear on Windows 10, Ctrl+Shift+N works.

**Comment by teevans** [comment]
Changing the keybinding to just <C-n> works. I'm wondering if there is a default keybinding somewhere else that keeps <S-C-n> working.

**Comment by breja** [comment]
The dismiss keybinds are handled before they get to neovim. `CSN` should be `Ctrl` + `Shift` + `N` and maybe `Cmd` instead of Ctrl on MacOS.

I'll try it out on Ubuntu and see what I can find.

**Comment by wmonk** [comment]
Same issue on MacOS, have tried with both cmd and ctrl.

**Comment by saforem2** [comment]
Same issue here

**Comment by darylducharme** [comment]
I'm having the same issue on linux. Some notifications can be dismissed by Ctrl + Shift + N but most get stacked.

**Comment by sc0** [comment]
> Changing the keybinding to just `<C-n>` works. I'm wondering if there is a default keybinding somewhere else that keeps `<S-C-n>` working.

@teevans How did you manage to change the keybind? Can't find it anywhere

**Comment by teevans** [comment]
@sc0 Sorry for the late response.  I actually changed it in the code base and recompiled. src/components/messages.ts Line 269 on my current branch.
