### ISSUE TITLE
Installed 1 VSCode Extension appears at each launch

### ISSUE THREAD

**Issue by teevans** [veonim/veonim#613]
At each launch the editor will 'Download' a VSCode extension.

**Comment by teevans** [comment]
Looks like it's the ms-vscode.go package that keeps being re-downloaded. Currently investigating.

**Comment by breja** [comment]
So just to clarify, the extension is downloaded every time veonim is launched, but only once per session? If it's being re-downloaded, then it probably fails to install at some point (fully download, unzip, copy, etc.).

I will try out `ms-vscode.go` and see if I can replicate.

**Comment by hujianxin** [comment]
Did repreduce it

**Comment by breja** [comment]
This feature will be removed
