### ISSUE TITLE
Windows config

### ISSUE THREAD

**Issue by danieldaeschle** [veonim/veonim#617]
I didn't got it running under windows. Where is the config file?

**Comment by khalidchawtany** [comment]
It is your neovim's config file. It should be located at `C:\Users[UserName]\AppData\Local\nvim\init.vim`.

**Comment by danieldaeschle** [comment]
It didn't worked. I tried that. :(

**Comment by JaniM** [comment]
See #610

**Comment by danieldaeschle** [comment]
Yes i saw
