### ISSUE TITLE
Veonim's commands either not being execute or treat as invalid

### ISSUE THREAD

**Issue by felixfong227** [veonim/veonim#618]
## Basic information
OS: MacOS High Sierra (10.13.6)
Machine Type: Macbook Pro 2016 (15 inch)
Veonim Version: 0.22.0 (0.22.0.3339)

---

This small code snippet is my `init.vim` script so far

```
set number
syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set t_Co=256
set termencoding=utf-8
set encoding=utf-8
set fileencoding=utf-8

if exists('veonim')
    Veonim files
    VeonimExt 'ext-typescript-javascript'
    VeonimExt 'vscode:extension/eamodio.gitlens'
endif

```

The `Veonim files` command resolve in nothing, what I am expecting is Veonim will prompt the file selection dropdown menu, but what actually did happend is nothing was perfomred 🤔 

As for the `VeonimExt` command, it actually reolsve into an exception 🙈 

![image](https://user-images.githubusercontent.com/13918481/55067839-6a0f3a00-50bb-11e9-904e-815cc6575e42.png)

Not sure if I placed the `init.vim` script into the correct location

My placemnt is `~/.config/nvim/init.vim`

Thanks, really enjoy using this awesome editor 🎉

**Comment by breja** [comment]
Thanks for the detailed issue!

`VeonimExt` was removed in 0.22.0. The new syntax looks something like:

```
let g:vscode_extensions = [
  \'vscode.typescript-language-features'
\]
```

More info here: https://github.com/veonim/veonim/tree/master/docs#vscode-extensions

Once that's fixed, do you still see issues with `Veonim files`? I'm not sure if you intend to have the files menu be called on startup, but usually I map the files command to a keybind - e.g. `nnoremap <leader>f :Veonim files<cr>`

**Comment by felixfong227** [comment]
![image](https://user-images.githubusercontent.com/13918481/55076343-2115b080-50d0-11e9-91f4-6557b571497e.png)

Thank you very much @breja 😸 the VSCode extensions installing feature is now working as intended

And as for the "files menu being call at applicaiton start up", the I was just trying to to test the Veonim's build-in commands 😛 

But even when I reolsved the extensions installing issue, sadly the "files menu" comment stily dosen't work

**Comment by breja** [comment]
Does the files command work as a key binding?

**Comment by felixfong227** [comment]
![image](https://user-images.githubusercontent.com/13918481/55097735-69949480-50f7-11e9-92f6-7efcd0308476.png)

The remap command you provided earlier is working
