### ISSUE TITLE
Windows always [No Name]

### ISSUE THREAD

**Issue by danieldaeschle** [veonim/veonim#619]
Even if save safe the file or type `:e file`

**Comment by mrtylerzhou** [comment]
came across with the same problem

**Comment by breja** [comment]
Any particular OS?

**Comment by danieldaeschle** [comment]
Windows

**Comment by mzgnr** [comment]
also macOS

**Comment by breja** [comment]
The error shown in the screenshot is fixed on master.

**Comment by mrtylerzhou** [comment]
thank you sir for you quick response

**Comment by breja** [comment]
I can't help with Windows at this time since I don't have a Windows setup.
