### ISSUE TITLE
open veonim from command line

### ISSUE THREAD

**Issue by breja** [veonim/veonim#620]
So I can do `veonim memes.js`. Need to get command line arguments in main proc and pass to nvim. Can look at how VSCode does their startup scripts. At some point they need to be added to $PATH so I’m curious how that is done (i think there’s a script to run?)

**Comment by felixfong227** [comment]
Noted, already working on it actually

I might just finalize it by tonight 🇭🇰(UTC+8)

Something like:

`$ veonim new_dir/new_app.js`
