### ISSUE TITLE
[request] Add a veonim git-files command

### ISSUE THREAD

**Issue by wmonk** [veonim/veonim#624]
Firstly thanks for this project, i've been using it for the last few days to great success! The workspaces flow is something that i'd tried to recreate in terminal neovim through various plugins, but never managed to get it working properly. Now with a few keybindings opening and switching between projects is super straightforward.

I used to use [fzf.vim](https://github.com/junegunn/fzf.vim) for various things, but have been able to replace most of my existing workflow with native `:Veonim` commands. The only one missing, which would be a great addition is the equivalent of `GFiles?`, which shows a file list of only changed files.

Would you be interested in adding this to the native `:Veonim` commands, or is this better as a custom menu as described in the user guide?

Depending on your answer, i'd be more than happy to contribute if you point me in the right direction 😄

**Comment by breja** [comment]
Thanks for the kind words and I'm glad to hear that you found success!

The answer for adding more commands is more philosophical in nature. In an effort to keep Veonim part of "simple IDE" it's always hard to decide what makes sense to include as default and what makes sense to keep in user-land. I've already lost my way with the inclusion of things like the git status indicators in the statusline. Not everyone uses git as part of their workflow, but I suspect a large majority do, so to the majority the status feature is perhaps useful.

I've been thinking about adding a built-in git branch switcher menu for a few months now. I think the branch switcher and your git status files idea could be useful, especially if the menus included additional metadata.

So the short answer is: sure, I'm willing to entertain the idea. I think the changes could be largely additive so if the feature does not pan out, it will be easy to remove.

If you're interested on working on this, I would start with a new component in the `components` dir. Components get dynamically loaded by `galaxy.ts`:
https://github.com/veonim/veonim/blob/0909676b126533c26c0959d391e81b7a5f3fa24e/src/bootstrap/galaxy.ts#L34

I would probably copy a lot of the code from other components like `generic-menu` and `vim-switch`. The `onAction` method from `core/instance-api` is what binds a `:Veonim stuff` command to component function (usually `show`). For example in `vim-switch`:
https://github.com/veonim/veonim/blob/0909676b126533c26c0959d391e81b7a5f3fa24e/src/components/vim-switch.ts#L71

The git functions are in `support/git.ts`. In general I try to keep the project dependencies light, so thus far I have not needed to bring in an npm module for git functions. If you feel a package is needed and find something good, then we can bring in a package and optimize later if needed.

Each workspace instance runs in a separate worker thread, so there is some plumbing work to tie each instance of the `support/git.ts` to the main UI thread. Some examples here:
https://github.com/veonim/veonim/blob/0909676b126533c26c0959d391e81b7a5f3fa24e/src/workers/instance.ts#L23
and then in the UI thread:
https://github.com/veonim/veonim/blob/0909676b126533c26c0959d391e81b7a5f3fa24e/src/core/instance-api.ts#L67
which finally ends up here:
https://github.com/veonim/veonim/blob/0909676b126533c26c0959d391e81b7a5f3fa24e/src/components/statusline.ts#L359

The current git functions subscribe to events, but requesting a git status from the component would probably be an easier flow. You can see some other examples in `core/instance-api` and `workers/instance` for how request flows work.

Let me know if you have further questions.

**Comment by breja** [comment]
This is currently out of scope. I'd like to have a few more git integrations at some point, but that won't be any time soon. There are many great plugins that can handle these workflows today.
