### ISSUE TITLE
Apparently Windows thinks this is a virus?

### ISSUE THREAD

**Issue by ohlookitsderpy** [veonim/veonim#628]
<img src="https://i.imgur.com/eeaFGGx.png">

**Comment by breja** [comment]
Maybe electron is the virus? loljk

I'm not really sure how to approach this. I don't know if having signed binaries would help at all. It would be interesting if you got the same issue when building from source.

**Comment by ohlookitsderpy** [comment]
Going to try building this myself to see if I get the same issue.

**Comment by skylarmb** [comment]
@ohlookitsderpy did you build this yourself? What was the result?

**Comment by ohlookitsderpy** [comment]
ah, forgot to. gonna do now

**Comment by ohlookitsderpy** [comment]
<img src='https://u.derpyenterprises.org/f00657.png'>

attempted build did this when running it from dist

**Comment by skylarmb** [comment]
did you `npm install`?

**Comment by ohlookitsderpy** [comment]
tried both ``yarn`` and ``npm install``

**Comment by breja** [comment]
Closing this out because I dunno. I will try to keep node modules up to date and further reduce dependencies. As always it's best to build from source.
