### ISSUE TITLE
How to run on Linux

### ISSUE THREAD

**Issue by Funeoz** [veonim/veonim#630]
Because when I open veonim-0.22.0.zip, there's no executable. Or maybe we need to compile it but there are no instructions.

**Comment by breja** [comment]
Which linux distro are you on? Also did you have any luck with the AppImage?

There should be an executable included that should work without compilation. I will have to try the downloads on a linux box and see what's up.

By the way, if you're on Arch there is a package: https://aur.archlinux.org/packages/veonim

**Comment by Funeoz** [comment]
I'm on Kubuntu 18.10 . I tried the AppImage but I don't using this type of files. But when I go in the tar.gz file, I can't find an executable.

**Comment by breja** [comment]
I do not provide binaries anymore
