### ISSUE TITLE
error Failed at the veonim@0.22.0 start script 'node tools/start.js'.

### ISSUE THREAD

**Issue by kzos** [veonim/veonim#631]
npm ERR! Linux 4.15.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! veonim@0.22.0 start: `node tools/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the veonim@0.22.0 start script 'node tools/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the veonim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs veonim
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls veonim
npm ERR! There is likely additional logging output above.
[npm-debug.log](https://github.com/veonim/veonim/files/3025566/npm-debug.log)

Did anybody encounter this issue.

**Comment by breja** [comment]
Forgive me if I'm dense, but I don't see any error information for the `start.js` script. Can you try running the script directly (i.e. `node tools/start.js`) and see if there is any direct error output?

**Comment by kzos** [comment]
sorry for posting late,
when i did 
$node tools/start.js
I got below error:


local dev XDG_CONFIG_HOME dir: /home/sunshine/utils/veonim/xdg_config
cleaning build folder
copying index html
copying process-explorer html
copying assets
copying runtime files
copying extension dependencies
copying binaries
copying hyperapp
{ Error: ENOENT: no such file or directory, lstat '/home/sunshine/utils/veonim/extension_dependencies/node_modules'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/sunshine/utils/veonim/extension_dependencies/node_modules' }

**Comment by breja** [comment]
I think `npm install` should fix missing `extension_dependencies`. It runs `tools/postinstall.js` on `postinstall` event.
