### ISSUE TITLE
appimage: Icon in the wrong place

### ISSUE THREAD

**Issue by daenney** [veonim/veonim#632]
When extracting the AppImage the icon is in `/usr/share/icons/hicolor/0x0/apps/veonim.png` but that's not right. It should be in `256x256` instead of `0x0`, the latter doesn't make sense at all.

I suspect you might be missing some dependency during the AppImage build that renders it unable to correctly determine the image size?

**Comment by breja** [comment]
Hmm, that is strange. We use electron-builder to package the AppImage, so I'm not intimately familiar with how the AppImages are built, but I can double check the build configuration to see if I messed anything up (likely 😄 ).

**Comment by breja** [comment]
I don't have Linux to test this, but I will be redoing the building strategy anyways
