### ISSUE TITLE
How to enable mouse and scrolling?

### ISSUE THREAD

**Issue by karambaq** [veonim/veonim#633]
Hello, great project! 
I'm wondering how can I enable mouse support, I've tried `set mouse=a` but didn't seems to work, also I've tried to scroll by the touchpad and this doesn't work too.
I'm using MacOS Mojave with copypaste config.

**Comment by breja** [comment]
There is currently no mouse support in Veonim.

**Comment by ECourant** [comment]
@breja Are you accepting pull requests for mouse support? If one were to try to add it?

**Comment by breja** [comment]
Sure

**Comment by breja** [comment]
Closing as mouse support is out of scope right now.
