### ISSUE TITLE
I just got plain vim :(

### ISSUE THREAD

**Issue by dev-drprasad** [veonim/veonim#634]
I installed neovim binary and ran `nvim` from `bin` directory. Its just opened plain vim. Ofcourse name is like **neovim**

Its not at all looking like the one in hero image of README.md

Here is my neovim screenshot
![neovim](https://user-images.githubusercontent.com/22687681/55889524-cbacc980-5bce-11e9-9b81-f27cb73d031b.png)

**Comment by khalidchawtany** [comment]
The nvim binary is the same from neovim. You need to download the appropriate binary for you OS and look for Veonim binary. Foe example, Mac OS binary is namd Veonim.application.
