### ISSUE TITLE
Weird font in the standard buffer

### ISSUE THREAD

**Issue by whzup** [veonim/veonim#636]
There appears a weird font in the standard buffer which is quite weird. It only appears after opening the standard buffer, if I open a file, for example, the font looks alright. In addition, there are some graphic glitches but I think these issues are known. Thanks for this awesome piece of software though. :+1:

![veonim_font](https://user-images.githubusercontent.com/39431903/56236982-35274f00-608b-11e9-93d5-d67b8ecc2caa.png)

Software:
Veonim 0.22
Neovim 0.31
OS: OpenSUSE Leap 15

**Comment by breja** [comment]
Just to clarify, do you have a custom `guifont` set? And does the issue happen if you do set a custom `guifont`?

I suspect the issue might be timing around loading the bundled Roboto Mono font.

**Comment by whzup** [comment]
@breja I don't have a custom `guifont` set and it also happens if I set a custom `guifont`. Maybe that's part of the problem with WebGL? I'm really no expert in this matter but might be a good first guess :smile:

**Comment by christiaan-janssen** [comment]
It looks to me like the default fallback font when you dont have a font set. Are you sure you set the gui font correctly? 
Mine looks like this:

`set guifont=Source\ Code\ Pro`

**Comment by whzup** [comment]
@christiaan-janssen Thanks for the hint, but I don't have a custom font set. 😕

**Comment by whzup** [comment]
BTW, if I start veonim and execute, for instance, `:e $MYVIMRC` it also appears in this weird font.

**Comment by breja** [comment]
There is currently some hackery involved to load a custom Roboto Font in Veonim. This is cute but it's too much hassle and will be removed. Instead Veonim will use a platform-specific default font instead.
