### ISSUE TITLE
[WebGL] Syntax highlighting misbehaving, colors changing semi-randomly

### ISSUE THREAD

**Issue by taylorthurlow** [veonim/veonim#638]
I've taken some videos to illustrate the problem. This occurs on all color schemes I've tried, except for the default one. Here's a video of what happens after issuing a `colorscheme` command to set the color scheme manually:

https://streamable.com/5kwoy

Here's a video of what happens if I set the colorscheme in my `init.vim`:

https://streamable.com/zmgwr

I notice the following problems:
* Rendering indent lines from the [indentLine plugin](https://github.com/Yggdroot/indentLine) straight up doesn't work (or essentially is not visible) and sometimes is highlighted incorrectly
* Colors for certain things like strings and symbols (in Ruby in this case) are usually green (which is correct, given the color scheme) but sometimes changes to red, and seems to be able to be manipulated/messed with by putting the cursor on those lines
* Colors change drastically when they are on the current cursor line
* Line numbers are inconsistent - I expect all numbers except the current line to be a dark gray color instead of the green seen in the videos

I don't configure ANY color related things in my `init.vim`, except for setting the color scheme.

If there's any other information I can provide, I'd love to.

EDIT: I'm having some issues with the default color scheme now. All strings are red, foreground and background. I triggered this when searching a buffer with `/`. Not repeatable so far.:

![Screen Shot 2019-04-19 at 7 46 50 PM](https://user-images.githubusercontent.com/761640/56450585-0a800500-62dc-11e9-9a9d-b03f5b54f784.png)

**Comment by breja** [comment]
Thanks for the detailed issue report (especially the helpful videos).

Are you using the multiple vim instances feature? (e.g. `:Veonim vim-create`, `:Veonim vim-switch` etc). There have been some bugs for color highlights around that feature.

Also what machine (interested in the GPU mainly) and OS version are you on? Are you using an external monitor? I haven't tested the gl shaders across too many combinations, so there could be some work there to do.

**Comment by taylorthurlow** [comment]
Hi @breja, thanks for getting back.

I'm not using the multiple vim instances feature.

Regarding the GPU, it's a GTX 1080, on MacOS 10.13.6. It's a Hackintosh, so things are slightly complicated by the fact that Nvidia's driver support for MacOS has always been horrible. I have full graphics acceleration and no issues with any other software, for what it's worth. My integrated graphics are still enabled but unused - not sure if that makes a difference, seeing as I think Intel has some features that are usable regardless of the primary GFX adapter.

I'm using two external monitors, both over DisplayPort.

Cheers!

**Comment by Ae-Mc** [comment]
Have the same problem.
System Info:
![image](https://user-images.githubusercontent.com/43097289/76759864-9543db00-679d-11ea-8c6e-b2a2c7917e02.png)

GPU: GTX 1070
OS: Arch Linux with Linux Kernel 5.5.6-arch1-1 and Cinnamon 4.4.8
NVIDIA Driver Version: 440.59
I'm using two external monitors, both over DisplayPort.
I don't configure ANY color related things in my init.vim, except for setting the color scheme.
I've tried multiple themes, but they all have the same issue (including default and veonim).
That's how it looks:
![image](https://user-images.githubusercontent.com/43097289/76759440-b8ba5600-679c-11ea-9605-b68b2fd22d18.png)
