### ISSUE TITLE
always on home directory (linux)

### ISSUE THREAD

**Issue by caputchinefrobles** [veonim/veonim#643]
Regardless of where (directory/folder) I execute veonim, it always looks for files on ~/, then I need to put the whole file path starting from home dir to actually open it. 

I'm running Veonim on Linux Debian Buster, npm 6.9.0.

**Comment by breja** [comment]
So you're expecting that if you run `~/Documents/veonim` then the `:pwd` will be `~/Documents`?

I wonder how this would work for MacOS or Windows. Having Veonim set the current working directory to the directory it was started from would mean `:pwd` on MacOS would be `/Applications/veonim.app/Contents/MacOS/Resources/app` and maybe `C:\Program Files\veonim\` on Windows.

**Comment by caputchinefrobles** [comment]
I'll try to better explain: 

My veonim is installed on /usr/bin/veonim, while /usr/bin is on my $PATH, so I'm not running ~/Documents/veonim, I'm running veonim (which is in /usr/bin/) inside the folder ~/Documents. As expected for default behavior on vi, vim, neovim and so on (at least on tux environment), as soon as I call veonim inside a specific folder, it should look for files in ./ (current folder) primarily. 

Btw, thanks for the awsome work.

**Comment by nfode** [comment]
Is there any possibility to start veonim for the current folder? Like, `veonim .`?

**Comment by DanielPower** [comment]
This is an issue for me as well. It goes against every other editor I've ever used. No matter what directory I'm in when I launch veonim from the terminal, it always opens to my home directory. I also can't open files with veonim from the terminal.
`veonim myfile` just opens an empty veonim instance.

**Comment by edujtm** [comment]
For those using it on linux, You can hack this feature in the `init.vim` file using autocmd and environment variables:

```Vim
if exists('veonim')
   autocmd VimEnter * cd $PWD
endif
```

I tried improvising opening files from the command line, but I believe the arguments are not being passed to neovim, so there isn't much you can do.
