### ISSUE TITLE
Dead keys not being handled

### ISSUE THREAD

**Issue by gustavo-hms** [veonim/veonim#645]
I'm using a Brazilian keyboard on a pt_BR location. With these configurations, ~, ^, ', \` and " are dead keys and, as such, the combination `^+a`, for instance, should produce `â`, but only the letter `a` is inserted. No dead key is being handled at all.

OS: Linux (Solus OS distribution)
Veonim version: 0.22.0 AppImage

**Comment by breja** [comment]
This may be related to the fact that we get key events from the window instead of an HTML text input field (which respects system language settings and IME). Or maybe the key codes need to remapped before being sent to nvim...

**Comment by gustavo-hms** [comment]
I don't know if this helps, but nvim on a terminal works as expected.
