### ISSUE TITLE
Ibus is not working and make weird notification popup.

### ISSUE THREAD

**Issue by ndgnuh** [veonim/veonim#647]
I tried several Vietnamese engines, but none of them works.

(this is a video)
[![video](https://i.ytimg.com/vi/WZSoEjvHd3A/hqdefault.jpg)](https://youtu.be/WZSoEjvHd3A)

**Comment by breja** [comment]
Thanks for taking the time to put together the video - it's definitely helpful. I'm not familiar with ibus but as I understand it, it's in the same realm as IME/Input method? 

There is a similar issue in regards to IME - #622. Fixing that requires switching the key inputs to a HTML input field. That part is easy, but the hard part is making key hold/repeat work reliably across all platforms. I know Oni struggled with this and VSCode with vim extension also has this issue.

I think we may just have to implement a few different options and allow users to pick the most important behavior for their workflow.

**Comment by breja** [comment]
IME is not supported at this time. May revisit later when I have more free time.
