### ISSUE TITLE
cursor in term is in wrong place (term draws its own cursor)

### ISSUE THREAD

**Issue by breja** [veonim/veonim#65]

**Comment by deomitrus** [comment]
seems like a neovim issue to me. (also happens in oni)

cursor_goto in terminal always goes to last normal mode position. should open issue upstream

**Comment by goavn** [comment]
bufenter * if &buftype == 'terminal' hide cursor lol?

**Comment by deomitrus** [comment]
need to track normal vs insert mode - need to show cursor in normal

**Comment by deomitrus** [comment]
terminal does not report mode changes. fuck.

**Comment by deomitrus** [comment]
it seems to behave a little differently on recent versions of neovim...

**Comment by breja** [comment]
not my problem anymore
