### ISSUE TITLE
Paste from Windows (platform) clipboard?

### ISSUE THREAD

**Issue by kenny-evitt** [veonim/veonim#652]
I can't figure out how to paste from the Windows clipboard. The `*` and `+` registers are empty, <kbd>Ctrl</kbd>+<kbd>v</kbd>, and <kbd>Shift</kbd>+<kbd>Ins</kbd> don't paste from the clipboard in insert mode.

**Comment by breja** [comment]
There are no other user-facing facilities for clipboard functionality in Veonim besides what Neovim provides. It's certainly strange that the `*+` registers are empty. Might be worth investigating if we are doing something in the process that breaks those on Windows.

**Comment by kenny-evitt** [comment]
@breja Any ideas on where or how to start investigating this?

**Comment by breja** [comment]
Could try the bundled nvim binary to see if it works with the clipboard. I think the binary is inside the `binaries` folder.

**Comment by kenny-evitt** [comment]
@breja I ran `resources\app\build\binaries\neovim\bin\nvim.exe` and the normal mode command `"*p` worked.

**Comment by breja** [comment]
I can't help with Windows as I don't have a Windows setup

**Comment by kenny-evitt** [comment]
@breja No worries! I haven't been using Veonim much at all since I last commented but if you can think of anything I (or anyone with a Windows computer) could try or do to investigate this, I might be able to help.
