### ISSUE TITLE
Add install instructions to readme

### ISSUE THREAD

**Issue by rjcoelho** [veonim/veonim#655]
We have install instructions for developers .. but for users ?

**Comment by breja** [comment]
Ideally downloading and running the binaries from the github Releases page should do the trick. Could probably add some links in the readme/getting started section.

Does that answer your question or did I misunderstand?

**Comment by rjcoelho** [comment]
Yes it does! But can you add it to the README ? Also do we have a brew formula for it ?

**Comment by breja** [comment]
Added to readme.

There is a brew cask formula for it but I haven't tried it out myself:
https://formulae.brew.sh/cask/veonim
