### ISSUE TITLE
[floating window support] nvim_open_win breaks Veonim

### ISSUE THREAD

**Issue by glacambre** [veonim/veonim#656]
OS: Linux 5.0.0-37-generic 40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Neovim version: NVIM v0.5.0-279-ge922576bd (Appimage)
Veonim version: veonim.0.22.0.AppImage

I'm encountering issues implementing ext_multigrid properly in my own GUI and decided to ~~steal code~~ see how Veonim handled it, only to discover that running `:call nvim_open_win(0, v:true, { "width": 10, "height": 10, "focusable": v:true, "external": v:true })` seems to break Veonim: the newly-opened window is not displayed and the cursor looks it stayed in the previous window even though it actually moved to the new window. Running `call nvim_win_close(1002, v:false)` seems to be enough to go back to a working state.
I guess it's probably just an issue with the selected grid not being drawn?

**Comment by breja** [comment]
I have not implemented floating windows... yet. Should probably get working on that.
