### ISSUE TITLE
Node is not available from inside veonim

### ISSUE THREAD

**Issue by artursmirnov** [veonim/veonim#657]
I'm running macOS Mojave and have `node` installed via `nvm`. Everything works properly in both `zsh` and `neovim`:
```
:echo system("node --version")
-> v11.1.0
:echo system("which node")
-> /Users/artur/.nvm/versions/node/v11.1.0/bin/node
```
But when I run the same inside Veonim I get 
```
zsh:1: command not found: node
```
At first, I thought that it might be related to the `nvm` (not all env var are exported), but `node` executable also exists in `/usr/local/bin`:
```
$ /usr/local/bin/node --version
-> v13.7.0
```

Is there any workaround to get `node` executable available inside Veonim?

**Comment by breja** [comment]
I believe you, but I was not able to reproduce this on the 0.22.0 release (or master).

I know at one point in time Veonim did not inherit env vars correctly from the shells, but I don't remember when it was fixed.
