### ISSUE TITLE
C++ extension not working

### ISSUE THREAD

**Issue by pianocomposer321** [veonim/veonim#659]
I added the id ms-vscode.cpptools to g:vscode_extensions, and when I open a c++ file, I get an error:
"Error detected while processing function <SNR>39_NetrwBrowseChgDir:line 177"

Then when I type, no autocomplete window appears.

**Comment by pianocomposer321** [comment]
I think I know why this happened. I had downloaded an older version of Veonim a while ago, and I think I was running that one. It wouldn't have used the g:vscode_extensions variable, so it gave an error. I'm downloading the newest version now.

**Comment by pianocomposer321** [comment]
Never mind, I downloaded the latest version, and the error persists. I get the same error when opening a python file with the python extension in the list.

**Comment by breja** [comment]
vscode extension support is still a work in progress. It's strange that you're getting a vim error though. Extension errors would appear in the javascript console I think.

**Comment by pianocomposer321** [comment]
I tried again today, and I don't get an error anymore. I think it may have to do with conflicts with the tabnine extension that was installed before. But I'm not getting completion pop-ups either.

Also, I have another question. Are vscode extensions only for autocompletion, or can I use an extension such as [Project Templates](https://marketplace.visualstudio.com/items?itemName=cantonios.project-templates)? If this is possible, how would I envoke the extension?

**Comment by pianocomposer321** [comment]
I just tried calling completefunc manually, by typing :call completefunc()<cr>, and I got the error "unknown function: completefunc".

**Comment by breja** [comment]
Only language features (autocomplete, goto definition, refactoring, etc.). Maybe debugging in the future.

**Comment by pianocomposer321** [comment]
Does anyone have any idea why this is happening?

**Comment by breja** [comment]
The built-in extension host was never 100% compatible with all vscode extensions. By this point the built-in extension host has fallen very far behind in compatibility with the vscode API. The current approach is flawed and as such vscode extension support will be deprecated/removed.

There is new experimental work being done on [Tirion](https://github.com/veonim/tirion) which will instead attempt to create a bridge between Neovim and the Code Extension host without emulation. If that experiment is successful it will be integrated in Veonim.
