### ISSUE TITLE
Has the development stopped?

### ISSUE THREAD

**Issue by TheBdouilleur** [veonim/veonim#661]
Hello,
I really love Veonim, thank you very much! However, it seems like nothing has been committed since December 22 .
Have you stopped maintaining it? You shouldn't, it's so great!
Thank you

**Comment by breja** [comment]
no

**Comment by Incanus3** [comment]
yay for Occam's razor :)

**Comment by TheBdouilleur** [comment]
@Incanus3 What ???

**Comment by TheBdouilleur** [comment]
When is the next release planned ?

**Comment by breja** [comment]
I don't plan releases
