### ISSUE TITLE
better completion filter engine

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#72]
current filter engines assume matches starting at any place in the string, but i think it should only start at query[0]. look at ycm?

**Comment by deomitrus** [comment]
ycm doesn't base start index only. you can subsequence anywhere in the string. still, i think startings should be ranked higher

**Comment by goavn** [comment]
exception should be made if we matched `sua` for `saveUserAccount` - that should be ranked higher

**Comment by goavn** [comment]
a naive sorter

```javascript
const data = ['vader', 'hater', 'error']
const data2 = ['saveUserAccount', 'suave', 'sure']

const hasUpperCase = m => m.toLowerCase() !== m

const importantFirst = (m, query) => m
  .slice()
  .sort((a, b) => hasUpperCase(a) ? -1 : a.startsWith(query) ? -1 : 1)

const res = importantFirst(data, 'er')
const res2 = importantFirst(data2, 'sua')
```

makes some assumptions on how fuzzaldrin returns case-sensitive results
