### ISSUE TITLE
set frameless window as an option

### ISSUE THREAD

**Issue by goavn** [veonim/veonim#79]
parse from init.vim? could be slow...

don't forget to set autohidemenubar for windows
https://electron.atom.io/docs/api/browser-window/#winsetautohidemenubarhide

**Comment by deomitrus** [comment]
how? config needs to be parsed BEFORE window created... (create lightweight fork of config-reader for initial parsings?)

**Comment by deomitrus** [comment]
extract vim parsing from config-reader into shared module
