### ISSUE TITLE
veonim remote

### ISSUE THREAD

**Issue by deomitrus** [veonim/veonim#95]
open file in veonim buffer from terminal with a shell alias

**Comment by deomitrus** [comment]
- [ ] create http server (listen for paths, then cmd -> :e path)
- [ ] inject bash alias to curl path to http server

or create a script? script more portable than bash alias? but will it be a bash script? lol

**Comment by Mobilpadde** [comment]
Has this been merged? If so, how do I get it working? :smile:

**Comment by breja** [comment]
Yes, this was implemented as `vvim` inside terminals in veonim (i.e. does not work outside veonim).

Example: `vvim ~/.config/nvim/init.vim`

More info: https://github.com/veonim/veonim/blob/master/docs/readme.md#open-file-from-terminal-in-current-window

**Comment by Mobilpadde** [comment]
Oh, okay. Do you know when it we'll be able to open a folder from terminal? Like `code .`?
